language: scala
jdk: oraclejdk8
scala:
- 2.11.7
sudo: false
cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt/boot
script:
- sbt ++$TRAVIS_SCALA_VERSION dist
deploy:
  matrix:
  - provider: elasticbeanstalk
    bucket_name: elasticbeanstalk-us-east-1-822027063215
    region: us-east-1
    app: travis-test
    env: travisTest1-env
    skip_cleanup: true
    zip-file: target/universal/travis-test-1.0-SNAPSHOT.zip
    on:
      repo: timatyork/travis-test
      branch: master
      condition: $TRAVIS_PULL_REQUEST = false
    access_key_id: AKIAJDGNTDP7O7SYG5VQ
    secret_access_key:
      secure: febIunkTZSR8Mz4mFQ9UTilmx0KdVREi11I/K8X77rr0kxTUF9bfWLcBq59kBZByRijm9fFl3DydT3tSepGFiTCTmTySTZZF4r+q6PqfolsM8a0EibBoVpoGerG9bjzBh2XhRlYWHQt0VKnRKZjcS/ln/DmJ1VT6W5z505y+XljowJg3YJ1eUt2CPBcbsP4eLv7GXLqntp/J4ejKhuteP7ZC9Piuw6QiWDcnAWTbStRfvz6IjCwwxZeB49Y5yKzZJKQDzd72q4cAla8QHctCZyZiRpSOsGmiJwlvGCdZRtbCxivEpGxzCW4Q8ZVrUMNN7pZ0ixW4+msQAUxg4nQqct55+niHc9qhKU3elRPrLyTx6K0oaLIjpLWF4Pp8+sWs1W7r3rB8DiMkILvSq3gkS2RcEPk6+mmrJFIbetERmz9VePQXs7pGpEHvOXNB2LvakVU84XFX7J84r4sWLqMc5L4aLADVTKXtCLZWNY39HyFU753ziKs2XvB2xCDI8iabPW6pwka11oax2KGXNk8OBonRenm0t/eIpF4azmFsSUklcPPNAeqQM067rfGJrKi0z9udlSh4lkD/Yi+V2iJLehrKWVWr76iQzWdcKs1WyZ8XPuWkMRRIuMDZEEEj+q47zPwVnZAltBG+MGtSyFzid3Gq7yIl4RSBD6OBaAIdghs=
